services:
  algrant_django:
    container_name: algrant_django
    build: ./django_app
    ports:
      - 8002:8000
    volumes:
      - algrant_django_volume:/var/lib/django/data
    networks:
      - algrantNet
    env_file:
      - .env
    restart: always

networks:
  algrantNet:
<<<<<<< HEAD
=======

volumes:
  algrant_django_volume:
  algrant_postgres_volume:
>>>>>>> dev
