services:
  algrant_django:
    container_name: algrant_django
    build: ./django_app
    ports:
      - 8002:8000
    networks:
      - algrantNet
    env_file:
      - .env
    restart: always

networks:
  algrantNet:
