services:
  algrant_postgres:
    container_name: algrant_postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      - algrant=value
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - algrant_postgres_volume:/var/lib/postgresql/data
    networks:
      - algrantNet  # Add this line to connect the database container to the network
    restart: always

  algrant_django:
    container_name: algrant_django
    build: ./django_app
    ports:
      - 8002:8000
    networks:
      - algrantNet
    env_file:
      - .env
    restart: always

networks:
  algrantNet:

volumes:
  algrant_postgres_volume:
