services:
  algrant_django:
    container_name: algrant_django
    build: ./django_app
    ports:
      - 8002:8000
    volumes:
      - algrant_django_volume:/var/lib/data
    networks:
      - algrantNet
    env_file:
      - .env
    restart: always

  adminer:
    env_file:
      - ./.env
    container_name: adminer
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - algrantNet
    restart: always

networks:
  algrantNet:

volumes:
  algrant_django_volume:
